### ISSUE TITLE
服务实例进程正常，服务与注册中心通讯不正常，耗时过久，导致在注册中心下线，这种情况如何修复

### ISSUE THREAD

**Issue by jerome2018** [huaweicloud/spring-cloud-huawei#1009]
**Describe the problem**
服务实例进程正常，服务与注册中心通讯不正常，耗时过久，导致在注册中心下线

**Sample code**
|WARN|Service Center Task [java.util.concurrent.ThreadPoolExecutor$Worker@764f0161[State = -1, empty queue][77]]|o.a.s.s.t.ServiceCenterTaskMonitor|endCycle||||51|||sc task taken more than 16489ms to execute

**Information**
service-center-1.3.0

**Comment by jerome2018** [comment]
重启服务后解决了，但是不清楚在注册中心下线的原因，网络问题可以排除

**Comment by lbc97** [comment]
日志能不能给多点儿 你们框架版本是多少 看起来就是链接超时导致的

**Comment by jerome2018** [comment]
框架版本：org.apache.servicecomb:java-chassis-dependencies-springboot2:1.3.0
在业务日志中涉及与servicecenter相关的只有上面那一条，sc的日志还不知道咋看

**Comment by lbc97** [comment]
如果你用的java chassis 就去java chassis社区下面提issue吧 把你的业务日志给全点儿  sc的日志如果你用的云上引擎你是看不了的  这是spring cloud huawei的社区
