### ISSUE TITLE
启动网关时候报错

### ISSUE THREAD

**Issue by YuGuoYun901006** [huaweicloud/spring-cloud-huawei#1051]
**Describe the problem**

提示java.lang.NoClassDefFoundError: feign/httpclient/ApacheHttpClient

**Sample code**
![image](https://github.com/huaweicloud/spring-cloud-huawei/assets/130743164/ea3ae77f-f2f5-4a71-8ece-9a9645bb0b81)

![image](https://github.com/huaweicloud/spring-cloud-huawei/assets/130743164/b0e949f5-77d5-4023-9476-31549b182a97)

**Information**
![image](https://github.com/huaweicloud/spring-cloud-huawei/assets/130743164/243fddae-9291-4882-9f81-24c099805bb8)

Spring Cloud Huawei version: 1.10.11-2021.0.x
Spring Cloud version(optional):2021.0.5
Spring Boot version(optional):2.6.13
Spring version(optional): 5.3.23

**Additional context**

**Comment by chengyouling** [comment]
A simple gateway started don't need feign, maybe is your business have dependency, check and add third party dependencies.
