### ISSUE TITLE
希望SCH/ServiceComb支持通过一个环境变量来指定微服务注册到ServiceComb注册中心指定的环境

### ISSUE THREAD

**Issue by little-cui** [huaweicloud/spring-cloud-huawei#1273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

ServiceComb注册中心支持微服务注册到自定义环境下，部署系统部署微服务时会按部署时指定的环境修改微服务注册的环境信息。

**Comment by chengyouling** [comment]
在代码中硬获取环境覆盖设置配置文件，对使用客户是一个盲盒，不具备灵活性，很容易造成干扰，所以框架目前支持配置文件占位符方式获取环境变量，如：spring.cloud.servicecomb.discovery.address=${PAAS_CSE_SC_ENDPOINT:http://127.0.0.1:30100}
