### ISSUE TITLE
服务请求kie配置中心404

### ISSUE THREAD

**Issue by NiceMoon** [huaweicloud/spring-cloud-huawei#1275]
版本：1.9.4
问题描述：组件启动时请求kie响应404，导致组件启动失败
<img width="804" alt="1716188127148" src="https://github.com/huaweicloud/spring-cloud-huawei/assets/22215540/fef7c81b-8c8f-41ce-ab29-18b2c2da83be">

**Comment by NiceMoon** [comment]
麻烦专家帮忙看下

**Comment by chengyouling** [comment]
你这个引擎是你们自己部署的LOCAL-CSE还是云上的servicecomb引擎？
如果是linux的local-cse好像配置中心是问题
