### ISSUE TITLE
Service interface thread pool isolation

### ISSUE THREAD

**Issue by xingguang2013** [huaweicloud/spring-cloud-huawei#1381]
**Is your feature request related to a problem? Please describe.**
Does spring-cloud-huawei support the provider-side thread pool isolation interface in the microservice of the cse/nacos registry center, so that the interfaces do not affect each other due to large traffic and long time consumption.

**Describe the solution you'd like**
Service interface thread pool isolation.

**Describe alternatives you've considered**
Similar to the specified interface configuration thread pool processing in RPC frameworks such as Dubbo

**Additional context**
none

**Comment by chengyouling** [comment]
not supported currently.
If you want use cse and support interface pool isolation, you can see https://github.com/apache/servicecomb-java-chassis
It will be more satisfying for your scene needs.
ths.

**Comment by xingguang2013** [comment]
I have a question: What are the differences in usage between [servicecomb-java-chassis](https://github.com/apache/servicecomb-java-chassis) and [spring-cloud-huawei](https://github.com/huaweicloud/spring-cloud-huawei), It looks similar, but there are some differences

**Comment by chengyouling** [comment]
1、for interface define
java-chassis defining Interfaces based on schema;
spring-cloud-huawei defining Interfaces based on restful;
2、for request
java-chassis base on vetx achieve async request, support hightway/http protocols
spring-cloud-huawei base on spring-cloud mvc/webflux request, support http protocols
3、for register/config
spring-cloud-huawei base on java-chassis interface achieve, but register process was base on spring-cloud.
