### ISSUE TITLE
服务开启异步调用，请求头做序列化时，报错空指针异常

### ISSUE THREAD

**Issue by Vientu** [huaweicloud/spring-cloud-huawei#1389]
**Describe the bug**
![image](https://github.com/user-attachments/assets/8c44ee64-e77a-4db0-8843-4ec0cae3ae99)
![image](https://github.com/user-attachments/assets/8fee5fe3-21c3-40ec-938d-6ff726db0145)
报错堆栈
![image](https://github.com/user-attachments/assets/0802f018-19a3-415a-81ab-55b7dce50a68)

**To Reproduce**
Sample code:

**Expected behavior**

**Information**

Spring Cloud Huawei version: 
Spring Cloud version(optional):
Spring Boot version(optional):
Spring version(optional): 

**Additional context**

**Comment by Vientu** [comment]
SDK版本 1.10.0-2021.0.X

**Comment by chengyouling** [comment]
1.10.0-2021.0.X之后增加null判断修复此问题
