### ISSUE TITLE
依赖管理错误

### ISSUE THREAD

**Issue by qiangtoudianyan** [huaweicloud/spring-cloud-huawei#162]
`<dependency>`
                `<groupId>com.huaweicloud</groupId>`
                `<artifactId>spring-cloud-huawei-dependencies</artifactId>`
                `<version>1.2.0</version>`
                `<type>pom</type>`
                `<scope>import</scope>`
            `</dependency>`
在当前这个版本中，指定了
`<spring-cloud.version>2.1.2.RELEASE</spring-cloud.version>`
    `<spring-boot.version>2.1.6.RELEASE</spring-boot.version>`
`为什么还要指定<spring.version>5.2.3.RELEASE</spring.version>，spring的版本本身对springmvc就是有版本依赖管理的现在这样指定版本是有冲突的spring-boot的版本过低导致spring的api不兼容，我们发布前不测吗？基本的应用启动都起不来。`

**Comment by GuoYL123** [comment]
https://github.com/huaweicloud/spring-cloud-huawei/pull/163/files

**Comment by GuoYL123** [comment]
https://github.com/huaweicloud/spring-cloud-huawei/pull/163

**Comment by GuoYL123** [comment]
后面会发布bug fix版本；临时解决方案可以在pom中覆盖声明 spring-web 、spring-webmvc的5.1.8.RELEASE依赖版本。

**Comment by qiangtoudianyan** [comment]
好的谢谢

**Comment by qiangtoudianyan** [comment]
是否可以考虑spring cloud huawei不去管理spring的版本交由spring boot本身去管理，这对我们做一些多方整合会更加方便

**Comment by liubao68** [comment]
Create application own dependencies management is always prefered. I can see every pobject, like spring, spring boot, servciecomb-java-chassis, spring-cloud-huawei have their own dependency management.

**Comment by qiangtoudianyan** [comment]
but spring boot already manage spring version.why we redefine spring version?
