### ISSUE TITLE
微服务移步注册方式

### ISSUE THREAD

**Issue by zengzefeng** [huaweicloud/spring-cloud-huawei#194]
com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
这个java类中涉及到服务注册的环境，里头的loopRegister反复注册的方法采用了while(true)的方式，微服务启动过程如果没有配置注册中心地址或者没有启动注册中心的话，会一直在这里做循环，主函数main中的SpringApplication.run后面的执行语句如打印服务启动成功日志会因此无法执行。
是否可以考虑优化成异步注册的方式，异步处理重试注册的场景？

**Comment by tianxiaoliang** [comment]
我同意用异步的方式进行注册，除此之外还要确保
1. 要用指数级退让来进行重新注册
2. while tue必须有跳出循环的机制

**Comment by liubao68** [comment]
服务启动的时候，如果服务中心不可用， 目前启动会退出。 这个对于并发启动的场景也不合适， 服务注册失败应该让服务启动起来， 在后台按照一定的策略定时尝试注册。

**Comment by tianxiaoliang** [comment]
嗯 我看了下go chassis实现的确是启动时，可以保证注册失败也启动，后续再进行尝试，没问题，就这么改吧

**Comment by GuoYL123** [comment]
代码已和入
