### ISSUE TITLE
spring-cloud-starter-huawei-servicecomb-discovery连接配置tsl的注册中心时是否支持密码明文加密

### ISSUE THREAD

**Issue by chenxiaoshou** [huaweicloud/spring-cloud-huawei#264]
我有一个配置了TSL的cse注册中心，后台服务已经通过TSL的方式注册到注册中心并可以接口访问。
现有一个springcloud服务，引入spring-cloud-starter-huawei-servicecomb-discovery，连接tsl的注册中心是否支持秘钥加密？

servicecomb后台服务的ssl配置如下：
![image](https://user-images.githubusercontent.com/14272090/94428791-ebb9b980-01c3-11eb-94b1-844f8e0bc0ee.png)

联系支撑人员，但是没有提供秘钥加密的方式。
https://github.com/huaweicloud/spring-cloud-huawei/tree/master/spring-cloud-huawei-sample/discovery-demo/ssl-demo

这里要如何对密码明文进行加密？是否有类似servicecomb的提供接口，支持用户自定义实现加密
![image](https://user-images.githubusercontent.com/14272090/94428978-33404580-01c4-11eb-9a97-52d04fac3234.png)

**Comment by liubao68** [comment]
please try 1.6.0-Hoxton. add same ssl configurations like servicecomb, but prefix is `spring.cloud.servicecomb.ssl`
