### ISSUE TITLE
governance feature

### ISSUE THREAD

**Issue by GuoYL123** [huaweicloud/spring-cloud-huawei#267]

**Comment by andyzhengyan** [comment]
Hi there, I got an error when tring to run this demo, there is **no explicit version** for artifact 'spring-cloud-starter-huawei-governance' in dependent pom 'spring-cloud-huawei-dependencies-1.3.1-Greenwich'.

I could run this demo after upgrade the version to 1.3.9-Greenwich.

You can get in touch with me by welink z00354939.

**Comment by liubao68** [comment]
这个需求包含了很多任务， 这个任务先关闭。 基于流量的治理功能预计在1.5.0包含初始功能和提供开发指南。
