### ISSUE TITLE
心跳报错org.apache.http.NoHttpResponseException: 

### ISSUE THREAD

**Issue by GuoYL123** [huaweicloud/spring-cloud-huawei#273]
由于long polling机制的存在，心跳时的sockettimeout时间即当前客户端的默认超时时间配置在50s。
服务中心对于单个实例的清理时间是healthCheckInterval * 3 , healthCheckInterval默认值是10s，也就是30s内没有心跳就会清理掉实例。
如果服务端(例如服务中心、apig hang住请求)太久没有返回，超过了默认30s的时间，就会导致实例被清理，从而导致了后续的心跳失败。(1.服务端会有定期清理空闲连接的机制，比如连接超过xx s自动清理，不会通知到客户端，如果客户端依然使用该请求，服务端会抛弃收到请求；2.服务端压力比较大时，会抛弃请求。 这两种情况可能都会导致服务端用长时间处理请求。)

解决方案：
规避：增加healthCheckInterval 的数值大小，这样可以忍受更长的服务端超时时间，延长清理实例的时间。
对应配置项：spring.cloud.servicecomb.discovery.healthCheckInterval ，建议配置30，默认单位为秒，如果依然出现错误可以继续延迟(不宜过长，会影响实例下线时间和实例故障的发现时间)。

todo: 客户端代码的优化，对于非long polling场景，缩短socket timeout的时间。

**Comment by GuoYL123** [comment]
改问题已经修复，但是没有发布版本；
新版本发布前只能采用规避方案：
设置spring.cloud.servicecomb.discovery.healthCheckInterval 
**部分场景配置30s仍然出错，建议配置到60s。**

表现形式不一定是NoHttpResponseException异常，在长时间运行报出大量
heartbeat failed.
都可以尝试使用该方法解决。

**Comment by GuoYL123** [comment]
建议升级版本到1.3.8+以上的版本，1.3.8改变了使用的心跳接口，缩短了socket timeout时间，一般可解决该问题。

**Comment by Cheirmin** [comment]
1.3.8-Greenwich 版本似乎也不可行。有啥推荐的版本吗？

**Comment by liubao68** [comment]
可以看看主页的版本： https://github.com/huaweicloud/spring-cloud-huawei
一般推荐用 Hoxton 版本， 其他版本 Spring Cloud已经停止维护， Spring Cloud Huawei的对不维护版本的支持也会逐步停止。 

BTW： 尽可能不要在closed的问题里面回复，容易被疏漏， 有问题可以提交新issue。
