### ISSUE TITLE
AK/SK加密保存的逻辑处理不恰当，不支持加密存储

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#282]
实现过程参考： https://github.com/apache/servicecomb-java-chassis/pull/2039/commits/bf9d5fb05042f149bf139efbcc3b2d9a03804222

目前实现不恰当。

**Comment by GuoYL123** [comment]
用spring boot的aop可以对配置进行加密，视频云已有实现，只需要写最佳实践文档即可

**Comment by liubao68** [comment]
`akskCustomCipher` 无意义了？
