### ISSUE TITLE
spring-cloud-huawei 1.2&1.3.7默认先读取fetching config的http://localhost:8888，然后超时报错

### ISSUE THREAD

**Issue by guodao** [huaweicloud/spring-cloud-huawei#287]
spring-cloud-huawei 1.2&1.3.7填写好了正确配置中心的参数，服务启动初始化还是会先读取fetching config的http://localhost:8888，抛出connect timeout异常，影响运维但不影响应用启动
请优化，避免运维人员定位问题。

**Comment by GuoYL123** [comment]
该问题可以参照demo，检查是否正确使用配置中心，尤其是配置文件的配置方式
https://github.com/huaweicloud/spring-cloud-huawei/tree/master/spring-cloud-huawei-sample/config-demo

**Comment by liubao68** [comment]
please try 1.6.0-Hoxton
