### ISSUE TITLE
spring-cloud-huawei 1.3.7指定了环境没不生效

### ISSUE THREAD

**Issue by guodao** [huaweicloud/spring-cloud-huawei#288]
spring-cloud-huawei 1.3.7 CSE上服务注册的时候不带环境名，导致都注册到默认环境上，而不是自己指定的比如development上

**Comment by GuoYL123** [comment]
手动配置环境 server.env: development 即可

**Comment by tianxiaoliang** [comment]
我们是否有文档写清了这个配置

**Comment by liubao68** [comment]
please try 1.6.0-Hoxton
