### ISSUE TITLE
springcloud-huawei1.3.7版本新增server.address等配置参数，编译会报错，用户完全不清楚该配置作用，及如何使用，请优化。

### ISSUE THREAD

**Issue by guodao** [huaweicloud/spring-cloud-huawei#289]
springcloud-huawei1.3.7版本新增server.address等配置参数，编译会报错，用户完全不清楚该配置作用，及如何使用，请优化。
如果是开关，请保持默认false状态。

**Comment by GuoYL123** [comment]
server.address 

是为了解决多网卡条件下的服务器ip暴露问题，配置改参数可以指定暴露的服务ip地址。
如：127.0.0.1 本地监听 ； 0.0.0.0 全网监听
该选项可以置空，会自动获取本地地址

**Comment by liubao68** [comment]
please try 1.6.0-Hoxton
