### ISSUE TITLE
springcloud-huawei1.3.7版本默认开启了websocket.watch=true，这个是高规格的CSE引擎才支持的特性，建议默认关闭。

### ISSUE THREAD

**Issue by guodao** [huaweicloud/spring-cloud-huawei#291]
springcloud-huawei1.3.7版本默认开启了websocket.watch=true，此配置专业版cse才提供的能力，基础版运行会报websocket连接超时。此类配置建议修改默认为关闭状态，高版本提示。

**Comment by GuoYL123** [comment]
watch关闭会很大程度上影响到服务故障/下线的响应时间，降低可用性，所以默认开启
当前版本手动关闭watch即可
spring.cloud.servicecomb.discovery.watch: false

**Comment by liubao68** [comment]
already changed wath to false
