### ISSUE TITLE
使用spring-cloud-huawei-route SDK，转发请求，在路由选择过程中报空指针

### ISSUE THREAD

**Issue by csuyinwei** [huaweicloud/spring-cloud-huawei#305]
![image](https://user-images.githubusercontent.com/14899491/101714579-ce16a380-3ad4-11eb-8485-3bed042e9346.png)

**Comment by csuyinwei** [comment]
SDK版本信息:1.3.7

**Comment by csuyinwei** [comment]
已经定位，老版本的注册地址支持这种形式，会导致匹配不到IP和端口的字符串，获取缓存实例信息为null，导致空指针
![image](https://user-images.githubusercontent.com/14899491/101714209-0c5f9300-3ad4-11eb-9d7a-677032dbd8ad.png)

**Comment by csuyinwei** [comment]
已经定位，老版本的注册地址支持这种形式，会导致匹配不到IP和端口的字符串，获取缓存实例信息为null，导致空指针
![image](https://user-images.githubusercontent.com/14899491/101714425-85f78100-3ad4-11eb-96f9-a94ab9473706.png)

**Comment by GuoYL123** [comment]
实例匹配是通过endpoint进行匹配，暂不支持后面加query字段这种形式

**Comment by csuyinwei** [comment]
通过前缀匹配，兼容老版本应该更合理
