### ISSUE TITLE
支持FeignClient针对部分服务不走注册发现

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#369]
具体用法参考：
https://stackoverflow.com/questions/50579935/is-it-possible-to-define-a-static-server-list-with-ribbon-via-feign-when-eurek

问题：
目前ServiceCombRibbonClientConfiguration获取serviceList的时候， 全部走了ServiceCombServerList， 没有考虑用户自定义配置的场景。

**Comment by develpoerX** [comment]
经过定位发现，spring-cloud-router-client中的RouterClientAutoConfiguration类中使用了@EnableFeginClients注解，指定了自定义的RouterFeginConfiguration.class类作为加载类，RouterFeginConfiguration中生成的bean中包含FeignCient类型，定义时，默认使用了loadblance类型的Client，@EnableFeginClients注解里面默认时，FeignClient类型是default。
因此，当用户引入spring-cloud-router-client模块后，再使用@FeignClient中url参数指定服务访问地址时，发生不生效。这是因为上面的逻辑破坏了FeignClient的原有逻辑，解决办法，1.不引用该模块（临时）。2.重新RouterFeginConfiguration类，参考@EnableFeginClients注解中default默认的类的实现，进行重写。

**Comment by liubao68** [comment]
Spring Cloud FeignClient调用第三方服务不走负载均衡的原理和文档参考： https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html

在 Spring Cloud Huawei场景下， 引入灰度发布模块后， 会定义默认的FeignClient和RibbonClient， 通过自定义第三方服务的RibbonClient即可实现不走负载均衡的功能。 示例代码已经提交。 参考issue关联的PR。
