### ISSUE TITLE
帮助文档的demo写错了吧？

### ISSUE THREAD

**Issue by andyzhengyan** [huaweicloud/spring-cloud-huawei#380]
![image](https://user-images.githubusercontent.com/14817533/114492959-307edc80-9c4c-11eb-8c97-5daeb43bf2bb.png)

应该是rules.match

[原代码地址](https://github.com/huaweicloud/spring-cloud-huawei/blob/master/spring-cloud-huawei-governance/README.md#%E5%9F%BA%E4%BA%8E%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E7%9A%84%E6%B5%81%E9%87%8F%E7%89%B9%E5%BE%81%E6%B2%BB%E7%90%86)

**Comment by develpoerX** [comment]
> ![image](https://user-images.githubusercontent.com/14817533/114492959-307edc80-9c4c-11eb-8c97-5daeb43bf2bb.png)
> 
> 应该是rules.match
> 
> [原代码地址](https://github.com/huaweicloud/spring-cloud-huawei/blob/master/spring-cloud-huawei-governance/README.md#%E5%9F%BA%E4%BA%8E%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E7%9A%84%E6%B5%81%E9%87%8F%E7%89%B9%E5%BE%81%E6%B2%BB%E7%90%86)



> ![image](https://user-images.githubusercontent.com/14817533/114492959-307edc80-9c4c-11eb-8c97-5daeb43bf2bb.png)
> 
> 应该是rules.match
> 
> [原代码地址](https://github.com/huaweicloud/spring-cloud-huawei/blob/master/spring-cloud-huawei-governance/README.md#%E5%9F%BA%E4%BA%8E%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E7%9A%84%E6%B5%81%E9%87%8F%E7%89%B9%E5%BE%81%E6%B2%BB%E7%90%86)

我们这里已经要下线这个问题，后续会使用我们最新的文档。新版文档链接：https://support.huaweicloud.com/devg-servicestage/ss-devg-0020.html

**Comment by liubao68** [comment]
fixed
