### ISSUE TITLE
华为云的服务治理与我们的代码中springCloud框架中的服务治理之间的异同不理解?

### ISSUE THREAD

**Issue by gwx988128** [huaweicloud/spring-cloud-huawei#407]
https://support.huaweicloud.com/usermanual-servicestage/servicestage_user_0456.html中的服务治理中与我们的代码中springCloud框架中的服务治理之间的异同是什么?我怎么实现?

比如:springCloud框架中的在我们的网关中实现了限流处理,但是我们在华为云上也有限流处理,这两者之间的异同是啥,我要怎么使用功能华为云上限流的功能的优势?

**Comment by develpoerX** [comment]
SDK端提供的限流，首先，你可以理解为更加细粒度的限流；其次，SDK作为一个框架接入，设定的场景并不是单纯的华为云场景。请注意我们治理策略的描述，是基于流量特征的治理。目前我们的限流粒度已经到了某一次请求流量的级别，这个比接口级别更加细粒度。详细的信息请参见：https://support.huaweicloud.com/devg-servicestage/ss-devg-0021.html

**Comment by gwx988128** [comment]
谢谢你精彩的解答
