### ISSUE TITLE
华为云灰度发布的操作步骤

### ISSUE THREAD

**Issue by gwx988128** [huaweicloud/spring-cloud-huawei#408]
现在我们想使用灰度发布的方式来发布我们的代码,我们也学习了https://support.huaweicloud.com/devg-servicestage/ss-devg-0023.html中,但是在操作的时候发现很难实现.有没有相关的文档.按照步骤进行操作就可以实现的.

**Comment by liubao68** [comment]
这个文档描述的只是微服务配置。 需要配合 servicestage 灰度发布界面操作， 可以完成老版本的平滑升级。 可以参考 ： https://support.huaweicloud.com/qs-servicestage/servicestage_qs_0093.html 体验下。

**Comment by gwx988128** [comment]
按照步骤打包,报了这个异常:[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.5.RELEASE/spring-boot-dependencies-2.3.5.RELEASE.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR8/spring-cloud-dependencies-Hoxton.SR8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/huaweicloud/spring-cloud-huawei-bom/1.5.6-Hoxton/spring-cloud-huawei-bom-1.5.6-Hoxton.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.3.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.5.RELEASE/spring-boot-dependencies-2.3.5.RELEASE.pom @ line 42, column 19
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Hoxton.SR8 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR8/spring-cloud-dependencies-Hoxton.SR8.pom @ line 49, column 19
[ERROR] Non-resolvable import POM: Could not transfer artifact com.huaweicloud:spring-cloud-huawei-bom:pom:1.5.6-Hoxton from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/huaweicloud/spring-cloud-huawei-bom/1.5.6-Hoxton/spring-cloud-huawei-bom-1.5.6-Hoxton.pom @ line 58, column 19
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.huaweicloud.samples:canary-application:1.0-SNAPSHOT (C:\Users\wWX1017620\Desktop\spring-cloud-huawei-samples-master\canary\pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.3.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.5.RELEASE/spring-boot-dependencies-2.3.5.RELEASE.pom @ line 42, column 19: Permission denied: connect -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Hoxton.SR8 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR8/spring-cloud-dependencies-Hoxton.SR8.pom @ line 49, column 19: Permission denied: connect -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact com.huaweicloud:spring-cloud-huawei-bom:pom:1.5.6-Hoxton from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/huaweicloud/spring-cloud-huawei-bom/1.5.6-Hoxton/spring-cloud-huawei-bom-1.5.6-Hoxton.pom @ line 58, column 19: Permission denied: connect -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by gwx988128** [comment]
这个要怎么操作才行?

**Comment by liubao68** [comment]
这个错误估计是内部网络设置问题，无法访问中央maven仓库，使用公司内部能够访问的中央仓库mirror即可。
