### ISSUE TITLE
spring-cloud-huawei-sample/gateway-demo/zuul-service无法正常启动

### ISSUE THREAD

**Issue by zhangchi02** [huaweicloud/spring-cloud-huawei#415]
zuul在获取serviceId时，ServiceCombRegistration抛出了一个异常，导致服务启动失败：
![image](https://user-images.githubusercontent.com/27462770/118785212-3a3ad600-b8c3-11eb-8bbf-d8e18a43f107.png)
代码修改记录：
![image](https://user-images.githubusercontent.com/27462770/118785330-58083b00-b8c3-11eb-8352-83f91146523e.png)

**Comment by develpoerX** [comment]
This problem should be caused by version incompatibility. Take a look at this case：https://github.com/spring-cloud/spring-cloud-netflix/issues/3314

**Comment by feihongyin** [comment]
大佬这个问题解决了吗？我也遇到这个问题了

**Comment by liubao68** [comment]
@feihongyin which version do you use?  You can refer to sample https://github.com/huaweicloud/spring-cloud-huawei-samples/tree/Hoxton/basic-zuul
