### ISSUE TITLE
目前会检查契约不相同，需要改版本号。 要求永远不改版本号，也能注册

### ISSUE THREAD

**Issue by develpoerX** [huaweicloud/spring-cloud-huawei#416]

**Comment by kaister3** [comment]
记得servicecomb那边有一个ignoreSwaggerDifference的配置，是同一个原理吗

**Comment by develpoerX** [comment]
> 记得servicecomb那边有一个ignoreSwaggerDifference的配置，是同一个原理吗

差不多，但又不完全一样，servicecomb那里原来的逻辑会从SC拉取服务schema的summary值，然后和本地当前的summary值进行比较，如果不一致，就在进行下一步操作。当时出问题是在这里，SCH没有这个操作流程，这个是客户的一个诉求，不是bug，当初那个是一个bug问题，你可以看看那个issue,对bug原因是有描述的
