### ISSUE TITLE
启动serviceStage服务后,运行日志显示不出来

### ISSUE THREAD

**Issue by gwx988128** [huaweicloud/spring-cloud-huawei#419]
我们现在在hcs环境上的serviceStage上,启动一个服务,在我们的运行日志这里就会有日志显示,不知道怎么回事,晚上我重新启动了服务,就是没有日志显示了?

**Comment by develpoerX** [comment]
根据你描述的问题，这个问题应该不是框架解释的，可以咨询一下serviceStage产品。如果是我们框架涉及的问题，麻烦你把问题描述的更清晰一些，就目前的描述，我看不出来哪里是涉及到了框架。
