### ISSUE TITLE
remove dtm module

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#432]
DTM have already provide a client, do not need adapter

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/pull/2425

**Comment by david6969xin** [comment]
close

**Comment by liubao68** [comment]
not fix now.

**Comment by liubao68** [comment]
Only remove dependency in spring-cloud-huawei-starter-service-engine
