### ISSUE TITLE
Spring Cloud Gateway使用spring-cloud-huawei的ServiceCombDiscoveryClient无法实现基于服务发现的路由定义功能

### ISSUE THREAD

**Issue by ctlove0523** [huaweicloud/spring-cloud-huawei#502]
问题现象：
运行spring-cloud-huawei-samples项目下basic包下的三个程序（三个程序向local cse注册成功），但是调用Spring Cloud Gateway没有注册其他三个服务（包括CSE自身）的路由信息。

问题原因：
`ServiceCombDiscoveryClient`对接口`List<String> getServices()`的实现使用的“懒加载”的方式，具体的分析如下：
`ServiceCombDiscoveryClient`定义了一个存储所有服务的`Set`
~~~
private Set<String> serviceIds = new HashSet<>();
~~~
Set的数据填充依赖对`List<ServiceInstance> getInstances(String serviceId)`方法的调用，如果没有调用该方法则`Set`一直为空。

Spring Cloud Gateway中`DiscoveryClientRouteDefinitionLocator`的实现方式是在构造函数中调用`ReactiveDiscoveryClient.getServices()`方法初始化所有服务信息：
~~~java
public DiscoveryClientRouteDefinitionLocator(ReactiveDiscoveryClient discoveryClient,
		DiscoveryLocatorProperties properties) {
	this(discoveryClient.getClass().getSimpleName(), properties);
	serviceInstances = discoveryClient.getServices()
			.flatMap(service -> discoveryClient.getInstances(service).collectList());
}
~~~
这时`ServiceCombDiscoveryClient.getServices()`返回空，导致Spring Cloud Gateway没有注册路由。

修改建议：
`getServices()`每次调用都直接从注册中心获取服务列表。

**Comment by liubao68** [comment]
`运行spring-cloud-huawei-samples项目下basic包下的三个程序（三个程序向local cse注册成功），但是调用Spring Cloud Gateway没有注册其他三个服务（包括CSE自身）的路由信息。`  

这个操作步骤是怎样的？ 我们运行samples并没有发现问题。

**Comment by ctlove0523** [comment]
> `运行spring-cloud-huawei-samples项目下basic包下的三个程序（三个程序向local cse注册成功），但是调用Spring Cloud Gateway没有注册其他三个服务（包括CSE自身）的路由信息。`
> 
> 这个操作步骤是怎样的？ 我们运行samples并没有发现问题。

1、首先在gateway这个项目下添加actuator依赖，并在配置文件中开启：
依赖
~~~xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
~~~
配置参数
~~~
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=gateway
~~~
2、调用actuator API获取gateway的所有路由信息
~~~
GET /actuator/gateway/routes
~~~
原来的API能调用，根本原因是gateway手动添加了一条路由
~~~java
@Bean
public RouteLocator routeLocator(RouteLocatorBuilder builder) {
return builder.routes()
	.route("basic-consumer", r -> r
		.path("/**")
		.uri("lb://basic-consumer"))
	.build();
}
~~~
Spring Cloud Gateway配置了下面的参数路由应该是自动注册的
~~~yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
~~~

**Comment by liubao68** [comment]
参考前面的PR， 你描述的问题测试了一下， 已经修复。
