### ISSUE TITLE
Spring Cloud Huawei在契约有变化但没修改版本号的情况下，自动更新契约

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#562]

**Comment by liubao68** [comment]
1. Spring Cloud Huawei运行时不依赖于契约， 自动更新可以查看到最新契约
2. service center扩大契约个数限制到500

**Comment by little-cui** [comment]
已经实现，详细看官网说明
https://support.huaweicloud.com/productdesc-cse/cse_productdesc_0004.html

**Comment by hujinming178** [comment]
问题的根本原因出在Apache/serviceComb/java-chassis中的底层逻辑中，只要在client/service-center-client中ServiceCenterRegistration类中的实例化成功逻辑后面添加 startTask(new RegisterSchemaTask(0));然后spring cloud huwei引用最新版本的servicecomb-java-chassis就可以实现契约的自动更新

**Comment by zhaozw** [comment]
我有以下几点疑问

1 如果是这种方式，就会每次无论契约有没有变化的时候都整体更新，是否需要作增量更新？
2 如果需要可以通过标志位来控制是否版本不变的情况下可以自动更新契约，因为可能其它第三方运行时可能依赖契约，觉得这里写死不是个好办法
3 在服务中心看到的契约是针对微服务和版本的，而不是实例的，这样是否会同一版本不同实例之间的契约不一样，而看到的只是最后启动的实例的版本，是我理解的这样吗？

**Comment by liubao68** [comment]
更新策略可以参考 servicecomb-java-chassis，简述如下：

1. 如果对应的schema id已经存在， 那么检查checksum是否相同，不同则覆盖；
2. 如果对应的schema id不存在，则创建一个新的

其他情况不处理做覆盖处理和删除处理。
