### ISSUE TITLE
依赖spring-cloud-starter-huawei-service-engine-gateway的网关项目如何实现重试策略

### ISSUE THREAD

**Issue by Giannuo** [huaweicloud/spring-cloud-huawei#566]
在网关应用上，使用了流量标记servicecomb.matchGroup，并配置了重试策略servicecomb.retry，调试代码时第一次失败后，重试报超时，SocketTimeoutException。
如何才能在网关应用上使用基于spring-cloud-huawei的重试

**Comment by m13922236379** [comment]
网关关于重试策略配置可以参考https://support.huaweicloud.com/devg-servicestage/ss-devg-0021.html一文。可通过配置retryOnResponseStatus响应码列表指定重试场景。重试规则借鉴了Resilience4j的思想，但是是不支持配置异常列表指定重试场景的。
另外我无法重现SocketTimeoutException这个异常，如果可以的话希望你能提供一个demo，我这边验证一下。

**Comment by liubao68** [comment]
@Giannuo  你的意思是 SocketTimeoutException 场景， spring-cloud-huawei没重试吗？

**Comment by Giannuo** [comment]
-
