### ISSUE TITLE
门禁检查引入SpotBugs

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#583]
参考： https://github.com/huaweicloud/spring-cloud-huawei/issues/81

分析下引入的可行性， 检查出来的问题数量等。

**Comment by YOC19970520** [comment]
具体分析检查出来的问题，评估修复难度有多大； 尝试引入github action，从maven配置进去，并设置合理的阈值，在保证主要问题修复了之后，CI能过，确保以后能够自动化检查新增问题
