### ISSUE TITLE
门禁检查引入PDM

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#584]
参考： https://github.com/huaweicloud/spring-cloud-huawei/issues/81

分析下引入的可行性， 检查出来的问题数量等。

**Comment by m13922236379** [comment]
可在Github Action中引入PMD检查，检查结果如下。
![image](https://user-images.githubusercontent.com/28680878/153983095-0a03418e-5a7c-41d6-bf90-75d0fe25e1b4.png)
修改/.github/workflows/maven.yml文件和在POM文件中增加Maven插件启用XML输出即可。
具体可参考https://github.com/jwgmeligmeyling/pmd-github-action

**Comment by liubao68** [comment]
https://github.com/huaweicloud/spring-cloud-huawei/pull/595
