### ISSUE TITLE
spring-cloud-huawei 1.8.0-2020.0.x版本是否支持netflix zuul

### ISSUE THREAD

**Issue by chenxiaoshou** [huaweicloud/spring-cloud-huawei#587]
spring-cloud-huawei 1.8.0-2020.0.x版本是否支持netflix zuul做网关路由转发，如果支持，请问下适配的是spring-cloud-netflix的版本是多少？如果不支持，是否只能使用spring-cloud-gateway做转发？

**Comment by YOC19970520** [comment]
1.8.0-2020.0.x版本暂时不支持zuul做网关路由转发,计划下个版本能够完成适配;

**Comment by YOC19970520** [comment]
我们下个版本已做好相关兼容

**Comment by chenxiaoshou** [comment]
请问下2020.x是否有哪个版本支持zuul的

**Comment by YOC19970520** [comment]
现在都暂不支持

**Comment by liubao68** [comment]
代码已经支持， 还没版本， 参考例子： https://github.com/huaweicloud/spring-cloud-huawei-samples/tree/master/basic-zuul

**Comment by liubao68** [comment]
try  1.8.1-2020.0.x
