### ISSUE TITLE
spring-cloud-gateway路由微服务时候是否支持发送https协议的请求

### ISSUE THREAD

**Issue by Zhuwanshun** [huaweicloud/spring-cloud-huawei#592]
此处代码没有实现是否有影响 com.huaweicloud.servicecomb.discovery.client.model.ServiceCombServiceInstance.isSecure() 。是否可以增加配置来实现。

**Comment by liubao68** [comment]
这种场景需要验证下，有可能是有影响的。

**Comment by m13922236379** [comment]
调试发现LoadBalancer通过判断ServiceCombServiceInstance.isSecure()来决定使用http/https转发。
将com.huaweicloud.servicecomb.discovery.client.model.ServiceCombServiceInstance.isSecure()改为true，gateway配置文件application.yaml中增加basic-provider.ribbon.IsSecure: true，网关即可通过https转发请求。配置中的basic-provider为服务名称。所以只要配置不同服务对应的IsSecure值即可支持对应服务的访问方式。

**Comment by m13922236379** [comment]
暂时无法正常使用https进行路由。暂定的升级方案是：根据所路由的微服务，自动选择https/http，而不是手动设置isSecure()值。
