### ISSUE TITLE
当healthCheckInterval配置的数值不合理时，元数据中healthCheckInterval应该是实际数值而非所配置的数值

### ISSUE THREAD

**Issue by david6969xin** [huaweicloud/spring-cloud-huawei#673]

**Comment by david6969xin** [comment]
servicecomb-service-center里面的healthCheckInterval数值范围为[1, Integer.MAX_VALUE]，而servicecomb-java-chassis中healthCheckInterval的范围限制在[1000, 600000]，因此当配置的数据不在这两个时间范围交集时，框架侧是不会报错，元数据healthCheckInterval得到的数值不是实际数值

**Comment by liubao68** [comment]
servicecomb-service-center里面的healthCheckInterval的单位是秒

**Comment by david6969xin** [comment]
从实际业务场景去考虑这个问题，似乎不会出现上述那样的配置数据场景

**Comment by david6969xin** [comment]
不修复，这种情况不太符合实际应用场景。
