### ISSUE TITLE
支持open api文档自动生成

### ISSUE THREAD

**Issue by tianxiaoliang** [huaweicloud/spring-cloud-huawei#68]
可以要求开发者写注解，service center支持契约的管理，期望服务启动后能够自动注册契约到service center中

**Comment by tianxiaoliang** [comment]
不用在本地生成，只需要上传到sc，并且能够通过访问/apidocs.json，将json格式的文档返回即可

**Comment by GuoYL123** [comment]
Java-chassis在生成swagger时，通过反射来获取方法相关信息，但反射机制的效率很低。
我在尝试通过spring mvc的一机制来获取bean的request url以及method相关信息。通过jackson的相关机制来获取参数和返回值bean的相关信息。从而避免对整个类的method进行反射扫描。
