### ISSUE TITLE
文档描述如何开发服务和调用服务

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#721]
1. 如何写RestController
2. 如何用RestTemplate调用、如何用Feign调用
3. 如何实现跨应用调用

**Comment by liubao68** [comment]
使用Spring Cloud Huawei功能
   -- 实现REST服务和调用REST服务

**Comment by comandowang** [comment]
不好意思,这个文档在哪里

**Comment by liubao68** [comment]
@comandowang  This is a tracking task, we are working on documents.
