### ISSUE TITLE
升级到1.10.1-2021.0.x版本RestTemplate声明为primary的问题

### ISSUE THREAD

**Issue by markey92** [huaweicloud/spring-cloud-huawei#771]
升级到1.10.1-2021.0.x版本，服务自身有多个RestTemplate的bean, 并且有一个定义成Primary
com.huaweicloud.governance.adapters.web默认定义一个RestTemplate的bean并且定义成@Primary，导致服务启动失败

**Comment by zhaozw** [comment]
spring.cloud.servicecomb.restTemplate.retryable.enabled设置为false 试试？

**Comment by liubao68** [comment]
集成spring cloud huawei的主体场景应该是使用CSE做负载均衡， 所以期望是使用其提供的RestTemplate， 以满足各种治理能力，包括客户端容错、熔断等。 参考：https://github.com/huaweicloud/spring-cloud-huawei/wiki/fault-client

所以设置primary，保证用户在声明的情况下优先使用spring cloud huawei是合理的。 你的场景是什么？

**Comment by Shoothzj** [comment]
同意 @liubao68 的看法，我们可能没有把这个变更点加到change notes中，服务自身之前定义的primary bean是用来做什么的？

**Comment by markey92** [comment]
> 集成spring cloud huawei的主体场景应该是使用CSE做负载均衡， 所以期望是使用其提供的RestTemplate， 以满足各种治理能力，包括客户端容错、熔断等。 参考：https://github.com/huaweicloud/spring-cloud-huawei/wiki/fault-client
> 
> 所以设置primary，保证用户在声明的情况下优先使用spring cloud huawei是合理的。 你的场景是什么？ 我们看下是否在你的场景需要用户使用primary。

**Comment by liubao68** [comment]
@markey92   你的回复消息只有引用，没内容，是不是丢了东西？

**Comment by markey92** [comment]
1、RestTemplte用于微服务间调用的client, 也用直接调用外部的rest client。有些微服务大部分是跟其它云服务交互的，不需要@LoadBalanced注解，这个定义primary，没啥问题啊

2、RestTemplte我们都不会直接用一个什么组件Autowired进来的，因为我们还要配置RestTemplte，连接池，超时时间，安全还要配置https的处理，业务通用的异常处理，所以spring cloud huawei定义的这个，我们业务不会用。

3、spring cloud common规范里面，RestTmplate加个@LoadBalanced注解就可以作为微服务的client，对业务侵入也少。也不要求一定要用它的bean

**Comment by Shoothzj** [comment]
> 1、RestTemplte用于微服务间调用的client, 也用直接调用外部的rest client。有些微服务大部分是跟其它云服务交互的，不需要@LoadBalanced注解，这个定义primary，没啥问题啊
> 是否考虑调用其他http接口使用非primary的一个注解
> 2、RestTemplte我们都不会直接用一个什么组件Autowired进来的，因为我们还要配置RestTemplte，连接池，超时时间，安全还要配置https的处理，业务通用的异常处理，所以spring cloud huawei定义的这个，我们业务不会用。
> 这个是否可以在spring-cloud-huawei框架里面配置？
> 3、spring cloud common规范里面，RestTmplate加个@LoadBalanced注解就可以作为微服务的client，对业务侵入也少。也不要求一定要用它的bean
这个规范有链接吗？

**Comment by liubao68** [comment]
谢谢 @markey92 详细补充， 我们在思考下如何优化下对于这块的处理

**Comment by liubao68** [comment]
不修改，建议冲突的场景配置 `spring.cloud.servicecomb.restTemplate.retryable.enabled=false`， 并进行额外自定义
