### ISSUE TITLE
升级到1.10.1-2021.0.x版本cse配置中心，经常回429

### ISSUE THREAD

**Issue by markey92** [huaweicloud/spring-cloud-huawei#775]
![18CF035B-0916-4AEC-9BA4-1071D41F1288](https://user-images.githubusercontent.com/13361383/176410072-b3500380-aad6-4506-b1e5-d0de773b3505.png)

**Comment by liubao68** [comment]
升级了 servicecomb  框架， 配置参数没加默认值

**Comment by markey92** [comment]
> 升级了 servicecomb 框架， 配置参数没加默认值

业务上怎么配置呢？

**Comment by liubao68** [comment]
你试试 `spring.cloud.servicecomb.config.configCenter.refreshInterval`  ， 这个值默认是0.
