### ISSUE TITLE
当前门禁检查不够严格，需要引入更多工具

### ISSUE THREAD

**Issue by tianxiaoliang** [huaweicloud/spring-cloud-huawei#81]
check style

coveralls

以及安全编程检查

**Comment by liubao68** [comment]
最紧要的事情可以将现在的 DEMO 示例做成自动化运行并校验运行结果。 因为该项目涉及的大部分代码都是和三方件交互和集成，这块自动化相对来说比较难做，但是如果没有自动化，很多修改不可能靠手工验证，所以还是需要尽可能补齐基本的集成的自动化测试用例。

**Comment by tianxiaoliang** [comment]
https://github.com/apache/servicecomb-kie/pull/147
看下这个，类似java这边肯定有更多的生态整合
找找，增强sch的静态扫描
https://github.com/securego/gosec
有的工具都会特意说自己集成了github action

**Comment by tianxiaoliang** [comment]
必须增加以下检查
- PMD
- SpotBugs
