### ISSUE TITLE
升级1.10.2-2021.0.x版本spring.cloud.servicecomb.discovery.enabled为false启动失败

### ISSUE THREAD

**Issue by haoke016** [huaweicloud/spring-cloud-huawei#812]
失败日志：
Parameter 0 of method restTemplateAddServiceNameContext in com.huaweicloud.servicecomb.discovery.context.RestTemplateContextConfiguration required a bean of type 'com.huaweicloud.servicecomb.discovery.registry.ServiceCombRegistration' that could not be found.

**Comment by liubao68** [comment]
什么场景不需要注册发现？Spring Cloud Huawei的主要功能之一就是为使用注册发现服务的。

**Comment by haoke016** [comment]
本地启动单机测试时，或者后续想直接使用istio时。如果不支持关闭，**spring.cloud.servicecomb.discovery.enabled**也就没有存在的意义了

**Comment by liubao68** [comment]
先解决配置项为false的时候，启动失败问题，后续针对isio场景，提供更加方便的服务发现支持。
