### ISSUE TITLE
spring-cloud-huawei 1.9.2-Hoxton灰度规则中配置header的规则，获取实例列表抛空值

### ISSUE THREAD

**Issue by markey92** [huaweicloud/spring-cloud-huawei#822]
![7515EE54-DC41-45DC-BE1A-40DE77A59926](https://user-images.githubusercontent.com/13361383/182343217-921d48e3-135f-4ed3-b21c-fd7c5bfe79d3.png)

**Comment by markey92** [comment]
realHeaders从RouterTrackContext.getRequestHeader中获取，是不是判一下空比较安全
![3A7F4AB4-816F-4C40-82B5-B6DBF9C36E71](https://user-images.githubusercontent.com/13361383/182344262-89c335bf-6b12-4853-9765-290abbc04836.png)

**Comment by liubao68** [comment]
你能提供下问题复现条件吗？

**Comment by markey92** [comment]
> 你能提供下问题复现条件吗？

灰度规则
- precedence: 2
  match:
    headers:
      x-domainid:
        regex: '0xxxxxxxxxxxxxxxxxxxxx0'
  route:
  - weight: 100
    tags:
     version: 2022.0802.1417.44
- precedence: 1
  route:
  - weight: 100
    tags:
     version: 2022.0801.2008.26
	 
代码调用，获取一个对端的实例信息
    @Autowired
    private LoadBalancerClient loadBalancer;

    /**
     * 获取服务实例，ribbon默认轮询策略
     * @param serviceName
     * @return
     */
    public ServiceInstance getOneInstance(String serviceName) {
        return loadBalancer.choose(serviceName);
    }

建议RouterTrackContext里面，header为null返回空Map
    public static Map<String, String> getRequestHeader() {
        if (requestHeaderThreadLocal.get() == null) {
            return Collections.emptyMap();
        }
        return requestHeaderThreadLocal.get();
    }

**Comment by liubao68** [comment]
spring-cloud-commons  的 LoadBalancerClient  和 Hoxton 无法一起使用； Hoxton需要使用Netflix的Ribbon。 这个问题关闭。
