### ISSUE TITLE
tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [huaweicloud/spring-cloud-huawei#894]
我正在做一个关于tag的调查研究。(很抱歉在这里打扰）
我们发现了1.5.3-Hoxton版本在maven中发布了，但是github中并没有相应的tag

1）请问tag缺失的原因是什么？（发现有相关pom修改信息）

- a、该版本存在代码问题，如存在漏洞、兼容性问题、界面方面问题等。
- b、该版本出现功能性问题，如功能规划不合理、基础功能不能使用等。
- c、忘记打tag
- d、不在意或者嫌操作麻烦
- e、该版本没有必要打tag
- f、其他原因，_

2） 针对该问题，我们提出了一个方法，能够找到version 可能对应的真实commit， 以帮助开发者快速定位问题代码，完成漏洞修复。 以下是我们方法给出的可能的真实commits，**请您帮忙确认下是否包含了真实的commit**，如果不是，应该是哪一个？
['8d0194d8720667936b962a0dd0a1b12f670c7708', '591963a835f21aec8519e4b792d0ffa6ef1e8cd6', '0a506ae9002ea314f64f90fbdb0baa1eecbeaffc']
这个问题对我们的调研非常重要，感谢能抽空解答QAQ

**Comment by liubao68** [comment]
请勿使用tag缺失的版本。
