### ISSUE TITLE
hession support need feign cutomization

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#908]
see : https://github.com/spring-cloud/spring-cloud-openfeign/issues/734
and https://github.com/huaweicloud/spring-cloud-huawei/blob/master/spring-cloud-starter-huawei/spring-cloud-starter-huawei-hessian/src/main/java/org/springframework/cloud/openfeign/support/ExtendedSpringEncoder.java

**Comment by mroccyen** [comment]
我可以试试吗

**Comment by liubao68** [comment]
@mroccyen 不好意思，没看到评论。 可以的， 不过这个修改openfeign还没新版本，作为issue先跟踪着。 我前期做了一个临时修改： https://github.com/huaweicloud/spring-cloud-huawei/pull/924  拷贝了这部分代码。 

如果你有更好的想法或者其他贡献，非常欢迎。

**Comment by liubao68** [comment]
Only fixed in 2022.0.x
