### ISSUE TITLE
配置中心如何根据key来获取值，因为涉及数组，不能指定参数名获取

### ISSUE THREAD

**Issue by WindSearcher** [huaweicloud/spring-cloud-huawei#979]
**Describe the bug**

**To Reproduce**
Sample code:

**Expected behavior**

**Information**

Spring Cloud Huawei version: 
Spring Cloud version(optional):
Spring Boot version(optional):
Spring version(optional): 

**Additional context**

**Comment by liubao68** [comment]
能给一个期望的例子吗？不是很理解

**Comment by WindSearcher** [comment]
executors:                                   # 动态线程池配置，都有默认值，采用默认值的可以不配置该项，减少配置量
        - threadPoolName: dtpExecutor3
          executorType: common                     # 线程池类型common、eager：适用于io密集型
          corePoolSize: 6
          maximumPoolSize: 8
          queueCapacity: 200
          queueType: VariableLinkedBlockingQueue   # 任务队列，查看源码QueueTypeEnum枚举类
          rejectedHandlerType: CallerRunsPolicy    # 拒绝策略，查看RejectedTypeEnum枚举类
          keepAliveTime: 50
          allowCoreThreadTimeOut: false                  # 是否允许核心线程池超时
          threadNamePrefix: test                         # 线程名前缀
          waitForTasksToCompleteOnShutdown: false        # 参考spring线程池设计，优雅关闭线程池
          awaitTerminationSeconds: 5                     # 单位（s）
          preStartAllCoreThreads: false                  # 是否预热所有核心线程，默认false
          runTimeout: 200                                # 任务执行超时阈值，目前只做告警用，单位（ms）
          queueTimeout: 100                              # 任务在队列等待超时阈值，目前只做告警用，单位（ms）
          taskWrapperNames: ["ttl"]                          # 任务包装器名称，集成TaskWrapper接口
          notifyItems:                     # 报警项，不配置自动会按默认值配置（变更通知、容量报警、活性报警、拒绝报警、任务超时报警）
            - type: capacity               # 报警项类型，查看源码 NotifyTypeEnum枚举类
              enabled: true
              threshold: 80                # 报警阈值
              platforms: [ding,wechat]     # 可选配置，不配置默认拿上层platforms配置的所以平台
              interval: 120                # 报警间隔（单位：s）
            - type: change
              enabled: true
            - type: liveness
              enabled: true
              threshold: 80
            - type: reject
              enabled: true
              threshold: 1
            - type: run_timeout
              enabled: true
              threshold: 1
            - type: queue_timeout
              enabled: true
              threshold: 1

**Comment by WindSearcher** [comment]
这样的又是如何映射过来，像notifyItems本身是一个数组，官网只有@Value和@RefreshScope

**Comment by chengyouling** [comment]
试试实现一个config类包含数组对象，监听ConfigurationChangedEvent事件，根据事件里面的key，刷新内容，可以参考：https://github.com/chengyouling/spring-cloud-huawei-samples/blob/master/basic/consumer/src/main/java/com/huaweicloud/samples/consumer/ConfigListen.java

**Comment by liubao68** [comment]
```
  List<XXXModel> models
```

这种情况spring是可以自动映射的。 在yaml里面可以配置成你给的例子。 



还是没太理解你的问题在什么地方。
