### ISSUE TITLE
关于网关路由的问题

### ISSUE THREAD

**Issue by ysjqaz** [huaweicloud/spring-cloud-huawei#990]
**bug位置**
spring-cloud-huawei-samples中的basic子项目

**bug描述**
关于网关路由规则的bug：路由规则是consumer，但是在微服basic-consumer上没有指定前缀，或者路径上没有关于"consumer"的配置，导致按照README_CN.md中的测试路径"http://localhost:9090/sayHello?name=World"请求时报404

**期望**
在微服、FeignClient、restTemplate请求路径上加上统一前缀consumer、provider

**信息**
spring-cloud-huawei-samples中的basic子项目
Spring Cloud Huawei version: 
Spring Cloud version(1.0-SNAPSHOT):
Spring Boot version(2.6.7):
Spring version(2.6.7): 

"问题确认后请联系我"
邮箱：1241267542@qq.com

**Comment by chengyouling** [comment]
请到samples下面提你的问题：https://github.com/chengyouling/spring-cloud-huawei-samples

**Comment by liubao68** [comment]
@chengyouling 可以修改下这个问题吗？

**Comment by chengyouling** [comment]
已经提交PR了

**Comment by liubao68** [comment]
@ysjqaz  problem fixed .  You can click "watch" to get notified for project activities.
