### ISSUE TITLE
客户端熔断配置策略，按照wiki配置不生效

### ISSUE THREAD

**Issue by BigG-King** [huaweicloud/spring-cloud-huawei#998]
**Describe the bug**
运行环境：北京四环境
在consumer模块，也就是客户端配置如下配置信息，熔断策略没有生效。
servicecomb:
  matchGroup:
    AllOperation: |
      matches:
        - apiPath:
            prefix: "/"
  instanceIsolation:
    AllOperation: |
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 20

是否需要修改成如下配置信息，把instanceIsolation修改成circuitBreaker
servicecomb:
  matchGroup:
    AllOperation: |
      matches:
        - apiPath:
            prefix: "/"
  circuitBreaker:
    AllOperation: |
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 20

**Comment by chengyouling** [comment]
配置错误码呢，我记得之前给你们走过一遍了，功能都OK的啊

**Comment by chengyouling** [comment]
好的，谢谢，我们看看怎么调整下
